version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo "Logging in to CodeArtifact..."
      - aws codeartifact login --tool maven --domain nextwork --domain-owner 721954953876 --repository nextwork-devops-cicd --region ap-south-1
  build:
    commands:
      - echo "Build started on `date`"
      - mvn clean install -DskipTests
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Packaging artifacts..."
      - mvn package -DskipTests

artifacts:
  files:
    - 'target/*.war'
  discard-paths: no
























